name: Build and Test Minecraft Server

on:
  workflow_dispatch:

jobs:
  run-server:
    runs-on: ubuntu-latest
    timeout-minutes: 355        # < 6 hours (GitHub limit)
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Java 21
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21

      - name: Create server directory
        run: |
          mkdir server && cd server
          wget -O paper.jar https://api.papermc.io/v2/projects/paper/versions/1.21.4/builds/1/downloads/paper-1.21.4-1.jar
          echo "eula=true" > eula.txt

      - name: Start Paper server (headless)
        working-directory: server
        run: |
          java -Xms6G -Xmx8G -jar paper.jar nogui &
          SERVER_PID=$!
          echo "Server PID: $SERVER_PID"
          # Keep it alive for testing time (e.g. 30 min)
          sleep 1800
          echo "Stopping server..."
          kill $SERVER_PID
          sleep 10

      - name: Upload world and logs
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: minecraft-server-output
          path: server
